.\" In .TH, FOO should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.\"
.\" This template provided by Tom Christiansen <tchrist@jhereg.perl.com>.
.\" 
.TH FOO SECTION 
.SH NAME
liteamp \- ogg and mp3 player for gnome
.SH SYNOPSIS
.PP
.B liteamp
.SH DESCRIPTION
.\" Putting a newline after each sentence can generate better output.
liteamp is a light-weigh music player for GNOME. It supports ogg and mp3 file fo
rmat.
.SH NOTES
homepage: http://liteamp.kldp.net
.SH BUGS
id3 and ogg-vorbis tag can't be modified.
The status icon(play/pause) in the playlist disappear by changing playlist while
playing.
.SH AUTHOR
Written by Dongsu Jang and Jacojang.
.SH "SEE ALSO"
.IR /usr/share/doc/liteamp/README .
contains several tips
